### ISSUE TITLE
BUG in Fields, Настройки => Поля 

### ISSUE THREAD

**Issue by samsonin** [samsonin/uchet-react#2]
в компоненте Fields
при нажатии на кнопку ОТМЕНА некорректно заменяется state компонента из redux-store, а именно fields.is_valid всегда false, в то время как в redux-store app.fields.allElements[n].is_valid значения разные

**Comment by nmgrinko** [comment]
Доброго времени суток. Мне интересны подобные задачи. Могу помочь.

**Comment by samsonin** [comment]
отлично! помогите пожалуйста

**Comment by nmgrinko** [comment]
ОК, только: 
Request URL: https://api.uchet.store/initial
Request Method: GET
Status Code: 401

**Comment by samsonin** [comment]
Да, для запуска используйте учетные данные из README

**Comment by samsonin** [comment]
// Логика:
    // в Redux-store храниться состояние с сервера
    // в componentDidMount это состояние переноситься в state
    // при добавлении, удалении и редактировании полей они меняются локально
    // при нажатии сохранить изменения отправляются на сервер и затем попадают в Redux-store
    // при нажатии Отмена требуется восстановить в state состояние из Redux-store
    // при удалении полей с is_system = true они не удаляются и выставляется флаг is_valid = false
    // при попытки восстановления состояния, некоторые поля с is_system не восстанавливают is_valid в true

**Comment by nmgrinko** [comment]
fieldsGlobalState() {
        return JSON.parse(JSON.stringify(this.props.app.fields.allElements))
    }

    componentDidMount() {

        const fieldsGlobalState = this.fieldsGlobalState()

        let fields = []
        fieldsGlobalState.map(v => {
            if (v.index === this.state.index) fields.push(v);
        
            // TODO исправить некорректное восстановление из Redux-store
            // при удалении полей с is_system = true они не удаляются и выставляется флаг is_valid = false
            // при попытки восстановления состояния, некоторые поля с is_system не восстанавливают is_valid в true

            if (v.name === 'prepaid') {
                console.log(v.is_valid)
            }
        })

        this.setState({
            fields,
            systemFieldsHandle: 0,
            customerFieldsCounter: 0
        })

    }

    indexHandle(index) {

        const fieldsGlobalState = this.fieldsGlobalState()

        this.setState({
            index,
            fields: fieldsGlobalState
                .filter(field => field.index === index)
        })
    }

**Comment by nmgrinko** [comment]
fieldsGlobalState() {
        return JSON.parse(JSON.stringify(this.props.app.fields.allElements))
    }

    componentDidMount() {

        const fieldsGlobalState = this.fieldsGlobalState()

        let fields = []
        fieldsGlobalState.map(v => {
            if (v.index === this.state.index) fields.push(v);

            // TODO исправить некорректное восстановление из Redux-store

// при удалении полей с is_system = true они не удаляются и
выставляется флаг is_valid = false

// при попытки восстановления состояния, некоторые поля с is_system не
восстанавливают is_valid в true

            if (v.name === 'prepaid') {
                console.log(v.is_valid)
            }
        })

        this.setState({
            fields,
            systemFieldsHandle: 0,
            customerFieldsCounter: 0
        })

    }

    indexHandle(index) {

        const fieldsGlobalState = this.fieldsGlobalState()

        this.setState({
            index,
            fields: fieldsGlobalState
                .filter(field => field.index === index)
        })
    }

сб, 25 июл. 2020 г. в 04:08, samsonin <notifications@github.com>:

**Comment by samsonin** [comment]
спасибо, проблема была в присвоении по ссылке

**Comment by samsonin** [comment]
скоро новые задачи опубликую, надеюсь на помощь )
